default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  username: myapp_user
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: myapp_test
  username: myapp_user
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: myapp_production
  username: myapp_user
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['MYAPP_DATABASE_HOST'] %>
  port: <%= ENV['MYAPP_DATABASE_PORT'] %>
